let a=50;
a++
console.log(a)
const b=200
b+
console.log(b)
var c=30
c++
console.log(c)
let alex1=5
alex1++
console.log(alex1)
const mussa=10
mussa+
console.log(mussa)
var richard=15
richard++
console.log(richard)
let number1=300
let number2=400
let result=number1+number2
console.log(result)
let number20=2024
let numbers=2023
let year=2025
let out=number20+year1+year
console.log(out)
function palindrom(str){
    let reversedstring=str.tolowercase().split('').reverse().join('')
    if(str===reversedstring){
        console.log(`${str} is a palindrom`)
    }
     else{
            console.log(`${str}is not a palindrom`)
        }
    return reversedstring
}
// console.log(palindrom(`dad`));
// console.log(palindrom(`MUM`));
// console.log(palindrom(`cat`));
palindrom(`DAD`)